/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MessageStatusResponse
    /// </summary>
    [DataContract]
    public partial class MessageStatusResponse :  IEquatable<MessageStatusResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageStatusResponse" /> class.
        /// </summary>
        /// <param name="timeStamp">The date/time the request was processed, in the format YYYYMMDDhhmmssSSS.</param>
        /// <param name="version">The current version of the API of the endpoint that was called.</param>
        /// <param name="statusCode">The http status code returned - reflected in the body for convenience.</param>
        /// <param name="messageStatuses">An array of ***messageStatus*** objects detailing the delivery status of each message .</param>
        public MessageStatusResponse(string timeStamp = default(string), string version = default(string), int? statusCode = default(int?), List<MessageStatus> messageStatuses = default(List<MessageStatus>))
        {
            this.TimeStamp = timeStamp;
            this.Version = version;
            this.StatusCode = statusCode;
            this.MessageStatuses = messageStatuses;
        }
        
        /// <summary>
        /// The date/time the request was processed, in the format YYYYMMDDhhmmssSSS
        /// </summary>
        /// <value>The date/time the request was processed, in the format YYYYMMDDhhmmssSSS</value>
        [DataMember(Name="timeStamp", EmitDefaultValue=false)]
        public string TimeStamp { get; set; }

        /// <summary>
        /// The current version of the API of the endpoint that was called
        /// </summary>
        /// <value>The current version of the API of the endpoint that was called</value>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }

        /// <summary>
        /// The http status code returned - reflected in the body for convenience
        /// </summary>
        /// <value>The http status code returned - reflected in the body for convenience</value>
        [DataMember(Name="statusCode", EmitDefaultValue=false)]
        public int? StatusCode { get; set; }

        /// <summary>
        /// An array of ***messageStatus*** objects detailing the delivery status of each message 
        /// </summary>
        /// <value>An array of ***messageStatus*** objects detailing the delivery status of each message </value>
        [DataMember(Name="messageStatuses", EmitDefaultValue=false)]
        public List<MessageStatus> MessageStatuses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MessageStatusResponse {\n");
            sb.Append("  TimeStamp: ").Append(TimeStamp).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  MessageStatuses: ").Append(MessageStatuses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MessageStatusResponse);
        }

        /// <summary>
        /// Returns true if MessageStatusResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of MessageStatusResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MessageStatusResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TimeStamp == input.TimeStamp ||
                    (this.TimeStamp != null &&
                    this.TimeStamp.Equals(input.TimeStamp))
                ) && 
                (
                    this.Version == input.Version ||
                    (this.Version != null &&
                    this.Version.Equals(input.Version))
                ) && 
                (
                    this.StatusCode == input.StatusCode ||
                    (this.StatusCode != null &&
                    this.StatusCode.Equals(input.StatusCode))
                ) && 
                (
                    this.MessageStatuses == input.MessageStatuses ||
                    this.MessageStatuses != null &&
                    this.MessageStatuses.SequenceEqual(input.MessageStatuses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeStamp != null)
                    hashCode = hashCode * 59 + this.TimeStamp.GetHashCode();
                if (this.Version != null)
                    hashCode = hashCode * 59 + this.Version.GetHashCode();
                if (this.StatusCode != null)
                    hashCode = hashCode * 59 + this.StatusCode.GetHashCode();
                if (this.MessageStatuses != null)
                    hashCode = hashCode * 59 + this.MessageStatuses.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
