/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessageRecipientDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageRecipientDetailsTests
    {
        // TODO uncomment below to declare an instance variable for MessageRecipientDetails
        //private MessageRecipientDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageRecipientDetails
            //instance = new MessageRecipientDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageRecipientDetails
        /// </summary>
        [Test]
        public void MessageRecipientDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageRecipientDetails
            //Assert.IsInstanceOfType<MessageRecipientDetails> (instance, "variable 'instance' is a MessageRecipientDetails");
        }


        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'ClientMessageId'
        /// </summary>
        [Test]
        public void ClientMessageIdTest()
        {
            // TODO unit test for the property 'ClientMessageId'
        }

    }

}
