/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MessageRecipientResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageRecipientResponseTests
    {
        // TODO uncomment below to declare an instance variable for MessageRecipientResponse
        //private MessageRecipientResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageRecipientResponse
            //instance = new MessageRecipientResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageRecipientResponse
        /// </summary>
        [Test]
        public void MessageRecipientResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageRecipientResponse
            //Assert.IsInstanceOfType<MessageRecipientResponse> (instance, "variable 'instance' is a MessageRecipientResponse");
        }


        /// <summary>
        /// Test the property 'ClientMessageId'
        /// </summary>
        [Test]
        public void ClientMessageIdTest()
        {
            // TODO unit test for the property 'ClientMessageId'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'Accepted'
        /// </summary>
        [Test]
        public void AcceptedTest()
        {
            // TODO unit test for the property 'Accepted'
        }
        /// <summary>
        /// Test the property 'AcceptError'
        /// </summary>
        [Test]
        public void AcceptErrorTest()
        {
            // TODO unit test for the property 'AcceptError'
        }
        /// <summary>
        /// Test the property 'ApiMessageId'
        /// </summary>
        [Test]
        public void ApiMessageIdTest()
        {
            // TODO unit test for the property 'ApiMessageId'
        }
        /// <summary>
        /// Test the property 'ScheduledTime'
        /// </summary>
        [Test]
        public void ScheduledTimeTest()
        {
            // TODO unit test for the property 'ScheduledTime'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }
        /// <summary>
        /// Test the property 'NewCreditBalance'
        /// </summary>
        [Test]
        public void NewCreditBalanceTest()
        {
            // TODO unit test for the property 'NewCreditBalance'
        }

    }

}
