/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewMessageDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewMessageDetailsTests
    {
        // TODO uncomment below to declare an instance variable for NewMessageDetails
        //private NewMessageDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewMessageDetails
            //instance = new NewMessageDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewMessageDetails
        /// </summary>
        [Test]
        public void NewMessageDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewMessageDetails
            //Assert.IsInstanceOfType<NewMessageDetails> (instance, "variable 'instance' is a NewMessageDetails");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Test]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'ScheduledTime'
        /// </summary>
        [Test]
        public void ScheduledTimeTest()
        {
            // TODO unit test for the property 'ScheduledTime'
        }
        /// <summary>
        /// Test the property 'MaxSegments'
        /// </summary>
        [Test]
        public void MaxSegmentsTest()
        {
            // TODO unit test for the property 'MaxSegments'
        }

    }

}
