/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShortcodeMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShortcodeMessageResponseTests
    {
        // TODO uncomment below to declare an instance variable for ShortcodeMessageResponse
        //private ShortcodeMessageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShortcodeMessageResponse
            //instance = new ShortcodeMessageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShortcodeMessageResponse
        /// </summary>
        [Test]
        public void ShortcodeMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShortcodeMessageResponse
            //Assert.IsInstanceOfType<ShortcodeMessageResponse> (instance, "variable 'instance' is a ShortcodeMessageResponse");
        }


        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Test]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'ResultsOffset'
        /// </summary>
        [Test]
        public void ResultsOffsetTest()
        {
            // TODO unit test for the property 'ResultsOffset'
        }
        /// <summary>
        /// Test the property 'ResultsLimit'
        /// </summary>
        [Test]
        public void ResultsLimitTest()
        {
            // TODO unit test for the property 'ResultsLimit'
        }
        /// <summary>
        /// Test the property 'ResultsTotalAvailable'
        /// </summary>
        [Test]
        public void ResultsTotalAvailableTest()
        {
            // TODO unit test for the property 'ResultsTotalAvailable'
        }
        /// <summary>
        /// Test the property 'ShortcodeMessages'
        /// </summary>
        [Test]
        public void ShortcodeMessagesTest()
        {
            // TODO unit test for the property 'ShortcodeMessages'
        }

    }

}
