/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubAccountsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubAccountsResponseTests
    {
        // TODO uncomment below to declare an instance variable for SubAccountsResponse
        //private SubAccountsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubAccountsResponse
            //instance = new SubAccountsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubAccountsResponse
        /// </summary>
        [Test]
        public void SubAccountsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubAccountsResponse
            //Assert.IsInstanceOfType<SubAccountsResponse> (instance, "variable 'instance' is a SubAccountsResponse");
        }


        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Test]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'SubAccounts'
        /// </summary>
        [Test]
        public void SubAccountsTest()
        {
            // TODO unit test for the property 'SubAccounts'
        }

    }

}
