/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing CreditTransferDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditTransferDetailsTests
    {
        // TODO uncomment below to declare an instance variable for CreditTransferDetails
        //private CreditTransferDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditTransferDetails
            //instance = new CreditTransferDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditTransferDetails
        /// </summary>
        [Test]
        public void CreditTransferDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditTransferDetails
            //Assert.IsInstanceOfType<CreditTransferDetails> (instance, "variable 'instance' is a CreditTransferDetails");
        }


        /// <summary>
        /// Test the property 'SendingAccountNumber'
        /// </summary>
        [Test]
        public void SendingAccountNumberTest()
        {
            // TODO unit test for the property 'SendingAccountNumber'
        }
        /// <summary>
        /// Test the property 'ReceivingAccountNumber'
        /// </summary>
        [Test]
        public void ReceivingAccountNumberTest()
        {
            // TODO unit test for the property 'ReceivingAccountNumber'
        }
        /// <summary>
        /// Test the property 'TransferQuantity'
        /// </summary>
        [Test]
        public void TransferQuantityTest()
        {
            // TODO unit test for the property 'TransferQuantity'
        }

    }

}
