/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing DeletedMessageStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeletedMessageStatusTests
    {
        // TODO uncomment below to declare an instance variable for DeletedMessageStatus
        //private DeletedMessageStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeletedMessageStatus
            //instance = new DeletedMessageStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeletedMessageStatus
        /// </summary>
        [Test]
        public void DeletedMessageStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeletedMessageStatus
            //Assert.IsInstanceOfType<DeletedMessageStatus> (instance, "variable 'instance' is a DeletedMessageStatus");
        }


        /// <summary>
        /// Test the property 'ApiMessageId'
        /// </summary>
        [Test]
        public void ApiMessageIdTest()
        {
            // TODO unit test for the property 'ApiMessageId'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Test]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'DeleteError'
        /// </summary>
        [Test]
        public void DeleteErrorTest()
        {
            // TODO unit test for the property 'DeleteError'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }

    }

}
