/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing IncomingOptoutMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IncomingOptoutMessageTests
    {
        // TODO uncomment below to declare an instance variable for IncomingOptoutMessage
        //private IncomingOptoutMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IncomingOptoutMessage
            //instance = new IncomingOptoutMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IncomingOptoutMessage
        /// </summary>
        [Test]
        public void IncomingOptoutMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IncomingOptoutMessage
            //Assert.IsInstanceOfType<IncomingOptoutMessage> (instance, "variable 'instance' is a IncomingOptoutMessage");
        }


        /// <summary>
        /// Test the property 'IncomingApiMessageId'
        /// </summary>
        [Test]
        public void IncomingApiMessageIdTest()
        {
            // TODO unit test for the property 'IncomingApiMessageId'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'ReceiveTime'
        /// </summary>
        [Test]
        public void ReceiveTimeTest()
        {
            // TODO unit test for the property 'ReceiveTime'
        }
        /// <summary>
        /// Test the property 'MessageText'
        /// </summary>
        [Test]
        public void MessageTextTest()
        {
            // TODO unit test for the property 'MessageText'
        }

    }

}
