/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing MessageStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageStatusTests
    {
        // TODO uncomment below to declare an instance variable for MessageStatus
        //private MessageStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageStatus
            //instance = new MessageStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageStatus
        /// </summary>
        [Test]
        public void MessageStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageStatus
            //Assert.IsInstanceOfType<MessageStatus> (instance, "variable 'instance' is a MessageStatus");
        }


        /// <summary>
        /// Test the property 'ApiMessageId'
        /// </summary>
        [Test]
        public void ApiMessageIdTest()
        {
            // TODO unit test for the property 'ApiMessageId'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'StatusDelivered'
        /// </summary>
        [Test]
        public void StatusDeliveredTest()
        {
            // TODO unit test for the property 'StatusDelivered'
        }
        /// <summary>
        /// Test the property 'StatusErrorCode'
        /// </summary>
        [Test]
        public void StatusErrorCodeTest()
        {
            // TODO unit test for the property 'StatusErrorCode'
        }
        /// <summary>
        /// Test the property 'StatusTime'
        /// </summary>
        [Test]
        public void StatusTimeTest()
        {
            // TODO unit test for the property 'StatusTime'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }

    }

}
