/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing OptoutMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptoutMessageResponseTests
    {
        // TODO uncomment below to declare an instance variable for OptoutMessageResponse
        //private OptoutMessageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OptoutMessageResponse
            //instance = new OptoutMessageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OptoutMessageResponse
        /// </summary>
        [Test]
        public void OptoutMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptoutMessageResponse
            //Assert.IsInstanceOfType<OptoutMessageResponse> (instance, "variable 'instance' is a OptoutMessageResponse");
        }


        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Test]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'IncomingOptoutMessages'
        /// </summary>
        [Test]
        public void IncomingOptoutMessagesTest()
        {
            // TODO unit test for the property 'IncomingOptoutMessages'
        }

    }

}
