/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing ScheduledMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduledMessageTests
    {
        // TODO uncomment below to declare an instance variable for ScheduledMessage
        //private ScheduledMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduledMessage
            //instance = new ScheduledMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduledMessage
        /// </summary>
        [Test]
        public void ScheduledMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduledMessage
            //Assert.IsInstanceOfType<ScheduledMessage> (instance, "variable 'instance' is a ScheduledMessage");
        }


        /// <summary>
        /// Test the property 'ApiMessageId'
        /// </summary>
        [Test]
        public void ApiMessageIdTest()
        {
            // TODO unit test for the property 'ApiMessageId'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'SubmitTime'
        /// </summary>
        [Test]
        public void SubmitTimeTest()
        {
            // TODO unit test for the property 'SubmitTime'
        }
        /// <summary>
        /// Test the property 'ScheduledSendTime'
        /// </summary>
        [Test]
        public void ScheduledSendTimeTest()
        {
            // TODO unit test for the property 'ScheduledSendTime'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }

    }

}
