/* 
 * WINSMS
 *
 * WinSMS RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@winsms.co.za
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using winsms.Api;
using winsms.Model;
using winsms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace winsms.Test
{
    /// <summary>
    ///  Class for testing SubAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubAccountTests
    {
        // TODO uncomment below to declare an instance variable for SubAccount
        //private SubAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubAccount
            //instance = new SubAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubAccount
        /// </summary>
        [Test]
        public void SubAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubAccount
            //Assert.IsInstanceOfType<SubAccount> (instance, "variable 'instance' is a SubAccount");
        }


        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'LoginName'
        /// </summary>
        [Test]
        public void LoginNameTest()
        {
            // TODO unit test for the property 'LoginName'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'CreditBalance'
        /// </summary>
        [Test]
        public void CreditBalanceTest()
        {
            // TODO unit test for the property 'CreditBalance'
        }

    }

}
